version: "3.3"

networks:
  production:
    name: production

services:
  server:
    image: janus/server:latest
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - MONGODB_USER
      - MONGODB_PASS
      - MONGODB_DATABASE
      - MONGODB_IP
      - MONGODB_PORT
      - PORT
      - PROJECT_NAME
      - API_PREFIX
    networks:
      - production
    restart: always
    command: yarn start:prod
