version: "3.3"

networks:
  production:
    name: production

services:
  server:
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT}
        reservations:
          memory: ${MEMORY_RESERVATIONS}
    image: janus/server:latest
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - MONGODB_USER
      - MONGODB_PASS
      - MONGODB_DATABASE
      - MONGODB_IP
      - MONGODB_PORT
      - PORT
      - PROJECT_NAME
      - API_PREFIX
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - production
    restart: always

