# Use root/example as user/password credentials
version: '3.3'

networks:
  production:
    name: production
services:
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGODB_EXPRESS_PORT}:${MONGODB_EXPRESS_PORT}
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASS}
      ME_CONFIG_MONGODB_PORT: ${MONGODB_PORT}
      VCAP_APP_PORT: ${MONGODB_EXPRESS_PORT}
    networks:
      - production
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_PORT: ${MONGODB_PORT}
      DB_NAME: ${MONGODB_DATABASE}
      DB_USER: ${MONGODB_USER}
      DB_PASSWORD: ${MONGODB_PASS}
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    command: --port ${MONGODB_PORT}
    networks:
      - production
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}